apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-07T12:31:39Z"
  generation: 1
  labels:
    app: personal-website
  name: personal-website
  namespace: default
  resourceVersion: "1246"
  selfLink: /apis/apps/v1/namespaces/default/deployments/personal-website
  uid: ab950645-a99c-4301-bf9d-3a5eafbbda61
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: personal-website
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: personal-website
    spec:
      containers:
      - image: gcr.io/personal-website-304111/resume-generator-react@sha256:1df3950820f9faef383e0ae381d71e350e2adb40c00b28872721085c1ea4f1e0
        imagePullPolicy: IfNotPresent
        name: resume-generator-react-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
